from configobj import ConfigObj
import argparse,codes3d

if __name__ == "__main__":
	parser = argparse.ArgumentParser(description="")
	parser.add_argument("-s","--snps_file",required=True,help="The list of SNPs generated by process_inputs.py")
	parser.add_argument("-c","--config",default="docs/conf.py",help="The configuration file to be used in this instance (default: conf.py)")
	parser.add_argument("-n","--include_cell_lines",nargs='+',help="Space-separated list of cell lines to include (others will be ignored). NOTE: Mutually exclusive with EXCLUDE_CELL_LINES.")
	parser.add_argument("-x","--exclude_cell_lines",nargs='+',help="Space-separated list of cell lines to exclude (others will be included). NOTE: Mutually exclusive with INCLUDE_CELL_LINES.")
	parser.add_argument("-o","--output_dir",default="hiCquery_output",help="The directory in which to output results (\"hiCquery_output\" by default).")
	args = parser.parse_args()
	config = ConfigObj(args.config)
	fragment_database_fp = config["FRAGMENT_DATABASE_FP"]
	hic_data_dir = config["HIC_DATA_DIR"]
	if not os.path.isdir(args.output_dir):
		os.makedirs(args.output_dir)

	snps = codes3d.parse_snps_file(args.snps_file)
	interactions = codes3d.find_interactions(snps,fragment_database_fp,hic_data_dir,args.include_cell_lines,args.exclude_cell_lines,args.output_dir)
