#!/usr/bin/env python

from configobj import ConfigObj
import argparse,codes3d,os

if __name__ == "__main__":
	parser = argparse.ArgumentParser(description="")
	parser.add_argument("-e","--eqtls_files",nargs='+',help="Space-separated list of one or more eQTL files generated by find_eqtls.py")
	parser.add_argument("-o","--output_dir",default="codes3d_summary",help="The directory in which to output results (\"codes3d_output\" by default).")
	parser.add_argument("-c","--config",default="docs/conf.py",help="The configuration file to be used in this instance (default: conf.py)")
	parser.add_argument("-f","--fdr_threshold",type=float,default=0.05,help="The FDR threshold to consider an eQTL statistically significant (default: 0.05).")
	args = parser.parse_args()
	config = ConfigObj(args.config)
	expression_table_fp = config["EXPRESSION_TABLE_FP"]
	eqtls,num_sig = codes3d.parse_eqtls_files(args.eqtls_files,args.fdr_threshold)
	if not os.path.isdir(args.output_dir):
		os.makedirs(args.output_dir)
	
	codes3d.produce_summary(eqtls,expression_table_fp,args.output_dir)