#!/usr/bin/env python

from configobj import ConfigObj
import argparse,codes3d,os

if __name__ == "__main__":
	parser = argparse.ArgumentParser(description="")
	parser.add_argument("-g","--genes_files",nargs='+',help="The list of genes generated by find_genes.py")
	parser.add_argument("-e","--eqtls_files",nargs='+',help="Space-separated list of one or more eQTL files generated by find_eqtls.py")
        parser.add_argument("-f","--fdr_threshold",type=float,default=0.05,help="The FDR threshold to consider an eQTL statistically significant (default: 0.05).")
	parser.add_argument("-o","--output_dir",default="codes3d_summary",help="The directory in which to output results (\"codes3d_output\" by default).")
	args = parser.parse_args()
	genes = codes3d.parse_genes_files(args.genes_files)
	eqtls,num_sig = codes3d.parse_eqtls_files(args.eqtls_files,args.fdr_threshold)
	if not os.path.isdir(args.output_dir):
		os.makedirs(args.output_dir)
	
	codes3d.produce_overview(genes,eqtls,num_sig,args.output_dir)
